{
 "title": "ICON2 Network Overview 202111",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Consensus Round Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "goloop_consensus_round_duration < 10000",
     "legendFormat": "{{prep_name}}"
    }
   ]
  },
  {
   "title": "Tx Pool Add Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "goloop_txpool_add_cnt", "legendFormat": "{{prep_name}}" }
   ]
  },
  {
   "title": "Consensus Height Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "goloop_consensus_height_duration < 10000",
     "legendFormat": "{{prep_name}}"
    }
   ]
  },
  {
   "title": "Difference in block height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "goloop_consensus_height - on() group_left() max(goloop_consensus_height)",
     "legendFormat": "{{prep_name}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "goloop_consensus_height", "legendFormat": "{{prep_name}}" }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "goloop_txlatency_commit", "legendFormat": "{{prep_name}}" }
   ]
  }
 ]
}